version: '3'

volumes:
  postgresql: 
    external: false

services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA= /var/lib/postgresql/data/pgdata # Default is already /var/lib/postgresql/data https://hub.docker.com/_/022689bf-dfd8-408f-9e1c-19acac32e57b
    volumes:  
      - postgresql:/var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: 10m
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1GB
          cpus: '0.1'

  webserver:
      image: puckel/docker-airflow:latest
      depends_on: 
        - postgres
      environment:
            - LOAD_EX=n
            - FERNET_KEY=81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs=
            - EXECUTOR=local
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
      ports:
        - "8080:8080"
      logging:
            options:
                max-size: 10m
                max-file: "3"
      volumes:
        - ./dags:/usr/local/airflow/dags # Loads docker dags
        - ./requirements_airflow.txt:/requirements.txt # Loads any requirements for Python in Docker

      command: webserver
      healthcheck:
          test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
          interval: 30s
          timeout: 30s
          retries: 3